---
title: "Wrangling Green Length Files"
author: "Bjorn Larson"
date: "2022-10-07"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

#Reading in data
```{r}
sag <-read.csv("Total Green Length - Sagwon.csv")%>%
  select(where(~ !(all(is.na(.)))))%>%
  select(-Average, -SD)#Removing empty columns
cold <-read.csv("Total Green Length - Coldfoot.csv")%>%
  select(where(~ !(all(is.na(.)))))%>%
  select(-Average, -SD)#Removing empty columns
tool <-read.csv("Total Green Length - Toolik.csv")%>%
  select(where(~ !(all(is.na(.)))))%>%
  select(-Average, -SD)#Removing empty columns
```

#Combining the three files into one dataset
```{r}
df_list <- list(sag, cold, tool)#Making list of the datasets

combined <-df_list%>%
  reduce(full_join)#combining the datasets
```
#Wrangling data for ease of use
```{r}
processed <- combined%>%
  pivot_longer(contains("X"), names_to = "DoY", values_to = "tot_Gr", values_drop_na = TRUE)%>%
  mutate(DoY = as.integer(substr(DoY, 2, 4)),#Making the day of year easy to use as a variable
         fullPlot = paste0(Loc, "-", Src, "-", Rep, Ind),
         Light = replace_na(Light, 0),
         OTC = replace_na(Light, 0),
         Shade = replace_na(Light, 0)#if the site didn't have OTCs, Lights, or Shades, marks as 0 instead of NA
  )%>%
  select(Light, Shade, OTC, Loc, Src, Rep, Ind, Plot, fullPlot, DoY, tot_Gr)
head(processed)#show the first 5 rows of the processed data
```

#Write processed dataset to new file
```{r}
write_csv(processed, "Total Green Length.csv")
```


