---
title: "Analyzing Results of Image Processing"
author: "Bjorn Larson"
date: "2022-08-18"
output:
  html_document:
    keep_md: true
---

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(lubridate)
library(plotly)
library(hms)
```

```{r}
site <- "CF" 
source <- "CF"
ind <- "3"
plot <- paste(site, source, ind, sep = "-")

read_phenocam <- function(path, tussock, ROI="RGB") {
  processed <- read.csv(path)%>%
    select(1:2 | contains(ROI))%>%
    mutate(datetime = ymd_hms(substr(img, 1, 19)),
           date = date(datetime),
           time = parse_hms(str_replace_all(substr(img, 12, 19), " ", ":")),
           site = site,
           source = source,
           ind = ind,
           plot = plot,
           tussock = tussock,
           excessG = .[[6]],
           pctG = .[[8]])%>%
    select('site', 'source', 'ind', 'plot', 'tussock', 'datetime', 'date', 'time', 'idx_label', 'excessG', "pctG")
  return(processed)
}

d <- read_phenocam("Phenocam_data/CF-CF-3_6.15-6.22.csv", "C")

d1 <- read_phenocam("Phenocam_data/CF-CF-3_6.22-6.29.csv", "C")

d2 <- read_phenocam("Phenocam_data/CF-CF-3_6.29-9.1.csv", "C", "31")

d3 <- read_phenocam("Phenocam_data/CF-CF-3_6.29-9.1.csv", "B", "32")

combined <- bind_rows(d, d1, d2, d3)
write.table(combined, "combined_phenocam_data.csv", sep = ",", append = TRUE, quote = FALSE, col.names = TRUE, row.names = FALSE)
```




```{r}
d <- read.csv("Phenocam_data/CF-CF-3_6.15-6.22.csv")%>%
  select(1,2,6,8)%>%
  mutate(datetime = ymd_hms(substr(img, 1, 19)),
         date = date(datetime),
         time = parse_hms(str_replace_all(substr(img, 12, 19), " ", ":")))%>%
  select('datetime', 'date', 'time', 'idx_label', 'RGB.2G_RBi', "RGB.pctG")
```

```{r}
d_rem<- read.csv("C:/Users/ecotypes/Downloads/takeout.csv")
d1 = d%>%
  filter(!idx_label %in% d_rem$Index)
```

```{r}
d2<-d%>%
  group_by(date)%>%
  summarize(median = median(RGB.2G_RBi))
d3 <- d %>%
  right_join(d2, d, by = 'date')%>%
  mutate(resid = RGB.2G_RBi - median)
```

```{r}
exif <- read.csv("CF-CF-9_exif.csv")%>%
  mutate(datetime = ymd_hms(CreateDate))
d5 <- right_join(d3, exif, by = "datetime")

plot_ly(d5, x = ~FileSize, y = ~resid, hovertext = paste0("Date:", d5$datetime))
```


```{r}
d4 = d3%>%
  filter(resid < 10)%>%
  filter(resid > -10)
#  filter(time > hms(00,00,07))
```


```{r}
toplot <- combined%>%
  filter(tussock == "B")%>%
  mutate(time_goodness = if_else(hms(0, 00, 09)< time & time < hms(0, 0, 14), "10:00-1:00", "Not 10:00-1:00"))
  filter(time > hms(0, 00, 09))%>%
  filter(time < hms(0, 0, 14))

plot_ly(toplot, x = ~datetime, y = ~pctG, hoverinfo = "text", color = ~time_goodness, hovertext = paste("Date: ", toplot$datetime, "<br>%G: ", toplot$pctG, "<br>Index: ", toplot$idx_label), type = "scatter", mode = "markers", colors = "Set1")%>%
  layout(xaxis=list(title = "Date"), yaxis = list(title = "Green Percent"))
  
```


```{r}
d5 <- d3%>%
  mutate(datetime = floor_date(datetime, unit = "hour"),
         time = as.factor(hour(datetime)))%>%
  group_by(time)

ggplot(d5, aes(y = resid, group = time))+
  geom_boxplot()+
  labs(y = "Distance from daily mean", x = "Time of Day")
```


