---
title: "Spectrometer_gif"
author: "Bjorn Larson"
date: '2022-06-17'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(gganimate)
library(leaflet)
library(htmltools)
library(shiny)
library(gifski)
library(photobiology)
library(transformr)
library(RColorBrewer)
library(plotly)
library(lubridate)
```

#read in dataset
```{r}
spectra <- read.csv("C:/Users/beeor/Downloads/Inside_Spectrometry.csv")%>%
  select(Time, X382nm:X768nm)%>%
  pivot_longer(!Time, names_to = "Wavelength", values_to = "Intensity")%>%
  mutate(Wavelength = as.numeric(substr(Wavelength, 2, 4)),
         Time = format(ymd_hms(Time), format= "%b %d %H:%M")
         )%>%
  group_by(Time)
```


#Functions
```{r}
#nmToRBG function
#takes wavelength and converts to RGB values
nmToRGB <- function(wavelength){
        Gamma = 0.80
        IntensityMax = 255
        if((wavelength >= 380) && (wavelength<440)){
            red = -(wavelength - 440) / (440 - 380);
            green = 0.0;
            blue = 1.0;
        }else if((wavelength >= 440) && (wavelength<490)){
            red = 0.0;
            green = (wavelength - 440) / (490 - 440);
            blue = 1.0;
        }else if((wavelength >= 490) && (wavelength<510)){
            red = 0.0;
            green = 1.0;
            blue = -(wavelength - 510) / (510 - 490);
        }else if((wavelength >= 510) && (wavelength<580)){
            red = (wavelength - 510) / (580 - 510);
            green = 1.0;
            blue = 0.0;
        }else if((wavelength >= 580) && (wavelength<645)){
            red = 1.0;
            green = -(wavelength - 645) / (645 - 580);
            blue = 0.0;
        }else if((wavelength >= 645) && (wavelength<781)){
            red = 1.0;
            green = 0.0;
            blue = 0.0;
        }else{
            red = 0.0;
            green = 0.0;
            blue = 0.0;
        };
        #Let the intensity fall off near the vision limits
        if((wavelength >= 380) && (wavelength<420)){
            factor = 0.3 + 0.7*(wavelength - 380) / (420 - 380);
        }else if((wavelength >= 420) && (wavelength<701)){
            factor = 1.0;
        }else if((wavelength >= 701) && (wavelength<781)){
            factor = 0.3 + 0.7*(780 - wavelength) / (780 - 700);
        }else{
            factor = 0.0;
        };
        if (red != 0){
          rf=red*factor
            red = round(IntensityMax * rf^Gamma);
        }
        if (green != 0){
          gf = green*factor
            green = round(IntensityMax * gf^Gamma);
        }
        if (blue != 0){
          bf = blue*factor
            blue = round(IntensityMax * bf^Gamma);
        }
        return(c(red,green,blue));
    }
```


```{r}
#hex_saver function
#protects leading zeros of Hexcodes
hex_saver <-function(number){
  number <- as.hexmode(number)
    return(format(number, width = 2))
}
```


```{r}
#rgbToHex function
#takes RGB values and converts to Hexcodes
rgbToHex <- function(color){
        #takes an 3 element array (r,g,b) and returns a hexadecimal color
        hexString = paste('#', hex_saver(color[1]), hex_saver(color[2]), hex_saver(color[3]), sep = "")
        return(hexString)
    }
```


```{r}
#w_2_H function
#Takes vector of wavelengths and returns vector of Hexcodes
w_2_H <- function(numbers){
  cols <- lapply(numbers, nmToRGB)
  hexs <- unlist(lapply(cols, rgbToHex))
  return(hexs)
}
```




#Plotting

```{r}
#rainbow dataframe
df <- data.frame(xmin = seq(382,768),
                 ymin = rep(-Inf, 387),
                 xmax = seq(383, 769),
                 ymax = rep(Inf, 387),
                 fill = seq(383, 769))%>%
  mutate(fill_cool = w_2_H(fill))

```

```{r}
p <- ggplot() +
  geom_line(data = spectra, aes( Wavelength, y = Intensity))+
  theme_classic()+
  geom_rect(data = df, aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax, fill = fill_cool), alpha = 0.5)+
  scale_fill_identity()
p
```

```{r}
create_date_time <- function(frame_var){
  Time = substr(frame_var, 8,13)
  Date = substr(frame_var, 1,6)
  paste("Date: ", Date, " Time: ", Time)
}
```


```{r}
anim <- p +
  transition_states(Time, transition_length = 0, state_length = 1)+
  labs(title = '{create_date_time(closest_state)}')+
  view_follow(fixed_x = TRUE, fixed_y = FALSE)
animate(anim, nframes =  288, fps = 12)
```

